### ISSUE TITLE
MathJax Rendering

### ISSUE THREAD

**Issue by banrovegrie** [asnunes/notion-page-to-html#14]
The MathJax rendering is erroneous. For example, it doesn't recognize `\\` as a marker for the equation to be rendered on the next line.

**Comment by asnunes** [comment]
Hi, @banrovegrie. Thank you for your report. Could you give some output example or public page where the problem is happening?

**Comment by banrovegrie** [comment]
Hey @asnunes, sorry for the late reply. Here, is an example of the rendering problem. 
- [Render](https://notion-page-to-html-api.vercel.app/html?id=9019f4ae60f1447890c10d6bb7881b0c)
- [Original](https://www.notion.so/banrovegrie/Proof-that-Bloch-Sphere-Unitaries-as-Rotations-9019f4ae60f1447890c10d6bb7881b0c)

**Comment by asnunes** [comment]
Hi @banrovegrie. Sorry for not getting back to you sooner. It seams to be a problem related to MathJax v3. There is an open [issue](https://github.com/mathjax/MathJax/issues/2312) about this on MathJax project. KaTeX seams to be the solution used by Notion project and it may feat better. I will consider migrate from MathJax to KaTeX on future releases.

In the mean time, you are free to open a PR or you may get only the html output from Notion page conversion and implement KaTeX on it.

Thank you for your report :)
