### ISSUE TITLE
404 on every page I've tried so far

### ISSUE THREAD

**Issue by anamba** [asnunes/notion-page-to-html#22]
After updating from 1.1.2 to 1.1.3, every page I try to read throws "Can not find Notion Page of id [id]. Is the url correct? It is the original page or a redirect page (not supported)?"

I looked through this, but still not sure why it is being triggered:
https://github.com/asnunes/notion-page-to-html/commit/e1904307f2c590d394d8f830528a64c5268b8432

Here are some example page ids that work with 1.1.2 but not 1.1.3:
22425fea05234ab282bb79f5b81881c4
640f9f67-56c6-4f6b-a371-81de2b2b16fd
71f15f9d-3da7-457d-b32e-b5363a402c2e
736b903b-3e9b-4dcd-973c-9262bb16f545

**Comment by kirill-konshin** [comment]
I  can confirm, even page from docs does not work: https://www.notion.so/asnunes/Simple-Page-Text-4d64bbc0634d4758befa85c5a3a6c22f

**Comment by turtledev-space** [comment]
The same issue, it works on `1.1.2` but always return `Page not found` on `1.1.3`

**Comment by asnunes** [comment]
Fixed on #25. Thank you all for reporting it
