### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by vladkrutenyuk** [asnunes/notion-page-to-html#26]
Uncaught (in promise) InvalidPageUrlError: Url "https://vladkrutenyuk.notion.site/Blog-Post-9173b6a515c54ad6bc9738f0001cd9af" is not a valid notion page. 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/42008771/159353188-667b07b7-5d79-4a44-8c4f-144a455a3224.png">

**Comment by vladkrutenyuk** [comment]
it doesnt work even with your link

**Comment by vladkrutenyuk** [comment]
![Uploading image.png…]()

**Comment by vladkrutenyuk** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/42008771/159353738-73f612e5-8d50-4337-9f5a-4d7c8c08cf4c.png"> 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/42008771/159353804-2663f426-1757-49aa-aeab-fe427d1ee4db.png">

**Comment by asnunes** [comment]
Hi, @vladkrutenyuk. Your given page is not public. Pages must be public to be fetched, also notion-page-to-html is a NodeJS tool, so it should not be used in the browser. That is why you are facing `node-http-post-client` error. Both informations can be found in the README.md file. Closing it by now.
