### ISSUE TITLE
Regex to adapt

### ISSUE THREAD

**Issue by alexguillon** [asnunes/notion-page-to-html#28]
Hi ! Thanks for this package ;)
But my notion URL is not `notion.so` but `notion.site` , I think that you'll need to adapt to accept other domain name.
Can I open a PR for that pls ? ;) 

https://github.com/asnunes/notion-page-to-html/blob/f0de0d77895bcfd71fa6b258e3b25dff82eb43bc/src/infra/usecases/to-page-id/url-validator.ts#L16

**Comment by samarthdave** [comment]
Bumping this, my URL `samarthdave.notion.site/...` is throwing an Invalid Page URL error and I've temporarily changed the code to:
```ts
private _isNotionPargeUrl(): boolean {
  return true;
}
```

Not ideal. Also it isn't getting the cover image or a table correctly... Might be because I hardcoded true in but I'm not sure.
