### ISSUE TITLE
resume releases?

### ISSUE THREAD

**Issue by fmiras** [asnunes/notion-page-to-html#32]
Hello! amazing project thanks to everyone involve and especially @asnunes 

I saw that there is no release since 5 months now, can we do a new release in NPM? I need this fix https://github.com/asnunes/notion-page-to-html/commit/c03060afa35c5f51ab831bf57f372da7b2c2835c so we can use it in a project 

For now I'll clone the project and publish it in a private npm repository.

**Comment by asnunes** [comment]
Hi, @fmiras. Thanks. I'm glad it is useful. A new release #33 (v1.2.0) is now available. It adds support to Notion's subdomains you mentioned
